### ISSUE TITLE
Mod causing all blocks to be unbreakable

### ISSUE THREAD

**Issue by Triliro** [62832/Fullblock-Energistics#2]
Heya, it seems that your implementation of the mine ability tag on pickaxes causes pickaxes to only be able to break blocks from your mod.

**Comment by 62832** [comment]
I cannot figure out why that may be happening. Are you on Forge or Fabric?

**Comment by Triliro** [comment]
Fabric and it was the 0.2 version, can get you a full mod list if you'd like.

**Comment by 62832** [comment]
Sure thing.

**Comment by TheAfroOfDoom** [comment]
@62832 I narrowed it down:

**problem:**

`fulleng:requester_terminal` does not load (correctly) if you don't have its dependency mod [ME Requester](https://modrinth.com/mod/merequester) installed (`merequester:requester_terminal`).

but `fulleng:requester_terminal` is still specified in the tag `minecraft:mineable/pickaxe`. so when the game tries to load said tag, we get the following error:

`Couldn't load tag minecraft:mineable/pickaxe as it is missing following references: fulleng:requester_terminal (from Fullblock Energistics)`

**solutions:**
- _ideal_: don't add `fulleng:requester_terminal` to the `minecraft:mineable/pickaxe` tag if ME Requester is not present <sup>don't know if this is possible? seems like it should be</sup>
- _less ideal_: change ME Requester to be a required dependency / have users install ME Requester (cc: @Triliro)

currently ME Requester is listed as an optional dependency (at least, according to [this release](https://modrinth.com/mod/fullblock-energistics/version/fabric-0.2)).

as soon as i installed ME Requester I was able to mine things with a pickaxe

**Comment by 62832** [comment]
That's actually extremely helpful, thanks for the heads-up.

Since I don't exactly know of a way to conditionally add blocks to the tag JSON yet, I may have to consider making the Requester terminal a dummy block in the event that ME Requester is not installed. Hopefully I'll have this out as a fix soon enough.

**Comment by 62832** [comment]
After much deliberation, I've come up with a patchwork fix for this due to come in build 0.3.

Please let me know if any problems still arise.
