### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Rogenar** [62832/Fullblock-Energistics#4]
fulleng-fabric-1.2-1.20.1 causes the game to crash without opening.
[latest.log](https://github.com/62832/Fullblock-Energistics/files/12251293/latest.log)
[crash-2023-08-03_16.26.28-client.txt](https://github.com/62832/Fullblock-Energistics/files/12251295/crash-2023-08-03_16.26.28-client.txt)

**Comment by 62832** [comment]
Should be fixed in the next release coming in about 5 minutes. Apparently I wasn't playing very nice with WTHIT.
